import type {
	SummonersCardDefinition,
	SummonersDeckId,
	SummonersStarterDeckDefinition,
} from "./summoners-types.ts"

function card(definition: SummonersCardDefinition): SummonersCardDefinition {
	return definition
}

export const summonersCardCatalog = {
	"ash-lesson": card({
		art: "✦",
		cost: 2,
		effects: [{ count: 2, kind: "draw" }],
		element: "fire",
		flavor: "Every scar remembers how the light got in.",
		id: "ash-lesson",
		name: "Ash Lesson",
		rules: "Draw 2 cards.",
		targeting: "none",
		type: "spell",
	}),
	"ashen-colossus": card({
		art: "♜",
		attack: 7,
		cost: 6,
		element: "iron",
		energy: 7,
		flavor: "The old kiln learned to walk and immediately chose trespass.",
		id: "ashen-colossus",
		keywords: ["guard"],
		name: "Ashen Colossus",
		rules: "Guard.",
		targeting: "none",
		type: "being",
	}),
	"barkhide-mouse": card({
		art: "♟",
		attack: 1,
		cost: 2,
		element: "wood",
		energy: 4,
		flavor: "Small enough to overlook. Stubborn enough to regret it.",
		id: "barkhide-mouse",
		keywords: ["rooted"],
		name: "Barkhide Mouse",
		rules: "Rooted. While it has 2 or more growth, it has Guard.",
		targeting: "none",
		type: "being",
	}),
	"blue-mile-leviathan": card({
		art: "≋",
		attack: 8,
		cost: 7,
		element: "water",
		energy: 8,
		flavor: "Maps call it a river because maps are cowards.",
		id: "blue-mile-leviathan",
		name: "Blue-Mile Leviathan",
		rules: "A very large reason to leave the ferry early.",
		targeting: "none",
		type: "being",
	}),
	"briar-challenge": card({
		art: "⌁",
		cost: 3,
		effects: [
			{ amount: 1, kind: "grow", recipient: "target" },
			{ kind: "ready", recipient: "target" },
		],
		element: "wood",
		flavor: "The hedge names its champion by closing behind them.",
		id: "briar-challenge",
		name: "Briar Challenge",
		rules: "Put a growth counter on a friendly Being, then ready it.",
		targeting: "friendlyBeing",
		type: "spell",
	}),
	"blooming-staff": card({
		art: "⌇",
		cost: 3,
		element: "leaf",
		flavor: "It takes root in the hand before the hand notices.",
		grantedKeywords: ["leech"],
		id: "blooming-staff",
		name: "Blooming Staff",
		rules: "Equipped Being gets +1/+2 and Leech.",
		targeting: "friendlyBeing",
		type: "item",
		attack: 1,
		energy: 2,
	}),
	"bone-needle": card({
		art: "⌁",
		attack: 2,
		cost: 2,
		element: "bone",
		energy: 0,
		flavor: "It stitches flesh, shadow, and inconvenient testimony.",
		grantedKeywords: ["leech"],
		id: "bone-needle",
		name: "Bone Needle",
		rules: "Equipped Being gets +2 Attack and Leech.",
		targeting: "friendlyBeing",
		type: "item",
	}),
	"borrowed-body": card({
		art: "↝",
		cost: 3,
		effects: [{ kind: "returnToHand", recipient: "target" }],
		element: "ether",
		flavor: "Return it when you are finished. Return most of it.",
		id: "borrowed-body",
		name: "Borrowed Body",
		rules: "Return a Being to its owner's hand. Its Item is discarded.",
		targeting: "enemyBeing",
		type: "spell",
	}),
	"brasshorn-ibex": card({
		art: "♞",
		attack: 4,
		cost: 3,
		element: "iron",
		energy: 4,
		flavor: "Realm surveyors have stopped measuring its charge distance.",
		id: "brasshorn-ibex",
		keywords: ["blaze"],
		name: "Brasshorn Ibex",
		rules: "Blaze.",
		targeting: "none",
		type: "being",
	}),
	"cancerous-bloom": card({
		art: "✺",
		cost: 5,
		effects: [
			{ amount: 4, kind: "damage", recipient: "target" },
			{ amount: 4, kind: "heal", recipient: "ownSummoner" },
		],
		element: "ether",
		flavor: "The cure and the curse share a root.",
		id: "cancerous-bloom",
		name: "Cancerous Bloom",
		rules: "Deal 4 damage to an enemy. Restore 4 life to your Summoner.",
		targeting: "anyEnemy",
		type: "spell",
	}),
	"canopy-muster": card({
		art: "❧",
		cost: 3,
		effects: [
			{ count: 2, kind: "draw" },
			{ amount: 1, kind: "heal", recipient: "ownSummoner" },
		],
		element: "leaf",
		flavor: "The forest votes by becoming impossible to cross.",
		id: "canopy-muster",
		name: "Canopy Muster",
		rules: "Draw 2 cards. Restore 1 life to your Summoner.",
		targeting: "none",
		type: "spell",
	}),
	"canopy-stag": card({
		art: "♞",
		attack: 3,
		cost: 4,
		element: "wood",
		energy: 5,
		flavor: "Its antlers remember every branch that made room for them.",
		id: "canopy-stag",
		keywords: ["rooted"],
		name: "Canopy Stag",
		rules: "Rooted. While it has 3 or more growth, it has Breakthrough.",
		targeting: "none",
		type: "being",
	}),
	"cinderwing-finch": card({
		art: "➶",
		attack: 3,
		cost: 2,
		element: "fire",
		energy: 1,
		flavor: "It migrates toward dry paperwork.",
		id: "cinderwing-finch",
		keywords: ["rush"],
		name: "Cinderwing Finch",
		rules: "Rush.",
		targeting: "none",
		type: "being",
	}),
	"chart-the-shoals": card({
		art: "⌖",
		cost: 3,
		effects: [{ count: 2, kind: "draw" }],
		element: "water",
		flavor: "A coastline is only a question the tide has not finished asking.",
		id: "chart-the-shoals",
		name: "Chart the Shoals",
		rules: "Draw 2 cards.",
		targeting: "none",
		type: "spell",
	}),
	"coalcoat-cub": card({
		art: "♟",
		attack: 2,
		cost: 1,
		element: "fire",
		energy: 1,
		flavor: "Warm paws. Bad alibi.",
		id: "coalcoat-cub",
		keywords: ["rush"],
		name: "Coalcoat Cub",
		rules: "Rush.",
		targeting: "none",
		type: "being",
	}),
	"dustmote-familiar": card({
		art: "※",
		attack: 1,
		cost: 1,
		element: "bone",
		energy: 2,
		flavor: "It purrs when someone nearby forgets their original shape.",
		id: "dustmote-familiar",
		keywords: ["leech"],
		name: "Dustmote Familiar",
		rules: "Leech.",
		targeting: "none",
		type: "being",
	}),
	"deep-roots": card({
		art: "⌇",
		attack: 0,
		cost: 3,
		element: "wood",
		energy: 2,
		flavor: "The earth keeps receipts for every creature it agrees to hold.",
		grantedKeywords: ["rooted"],
		id: "deep-roots",
		name: "Deep Roots",
		rules:
			"Equipped Being gets +2 Energy and Rooted. The first time each turn it would be spent or returned, remove 2 growth from it instead.",
		targeting: "friendlyBeing",
		type: "item",
	}),
	"elder-antler": card({
		art: "♜",
		attack: 6,
		cost: 6,
		element: "wood",
		energy: 8,
		flavor: "A whole remembered forest walks behind its eyes.",
		id: "elder-antler",
		keywords: ["leech"],
		name: "Elder Antler",
		rules: "Leech.",
		targeting: "none",
		type: "being",
	}),
	"flash-freeze": card({
		art: "❄",
		cost: 2,
		effects: [{ amount: 3, kind: "damage", recipient: "target" }],
		element: "ice",
		flavor: "A perfect moment, preserved somewhat too sharply.",
		id: "flash-freeze",
		name: "Flash Freeze",
		rules: "Deal 3 damage to an enemy Being.",
		targeting: "enemyBeing",
		type: "spell",
	}),
	"frontier-flareknife": card({
		art: "†",
		attack: 2,
		cost: 2,
		element: "iron",
		energy: 0,
		flavor: "Approved for brush, rope, dinner, and unlicensed miracles.",
		grantedKeywords: ["blaze"],
		id: "frontier-flareknife",
		name: "Frontier Flareknife",
		rules: "Equipped Being gets +2 Attack and Blaze.",
		targeting: "friendlyBeing",
		type: "item",
	}),
	"fruitful-sacrifice": card({
		art: "❦",
		cost: 2,
		element: "slime",
		flavor: "Nothing in the Compact is wasted. Some object to the definition.",
		id: "fruitful-sacrifice",
		name: "Fruitful Sacrifice",
		rules:
			"Destroy a friendly Being. Put a growth counter on each other friendly Being; if the sacrificed Being had growth, draw a card.",
		targeting: "friendlyBeing",
		type: "spell",
	}),
	"furnace-fox": card({
		art: "♞",
		attack: 5,
		cost: 4,
		element: "fire",
		energy: 3,
		flavor: "Its grin arrives one room before the heat.",
		id: "furnace-fox",
		keywords: ["leech", "blaze"],
		name: "Furnace Fox",
		rules: "Leech. Blaze.",
		targeting: "none",
		type: "being",
	}),
	"glacier-ram": card({
		art: "♜",
		attack: 4,
		cost: 4,
		element: "ice",
		energy: 6,
		flavor: "The mountain sent a smaller mountain to negotiate.",
		id: "glacier-ram",
		keywords: ["guard"],
		name: "Glacier Ram",
		rules: "Guard.",
		targeting: "none",
		type: "being",
	}),
	"green-reprisal": card({
		art: "⌁",
		cost: 3,
		effects: [{ amount: 4, kind: "damage", recipient: "target" }],
		element: "wood",
		flavor: "The hedgerow remembers every boot.",
		id: "green-reprisal",
		name: "Green Reprisal",
		rules: "Deal 4 damage to an enemy Being.",
		targeting: "enemyBeing",
		type: "spell",
	}),
	"gullwind-courier": card({
		art: "➶",
		attack: 2,
		cost: 2,
		element: "air",
		energy: 2,
		flavor: "Neither rain nor sleet nor a declared border.",
		id: "gullwind-courier",
		keywords: ["rush"],
		name: "Gullwind Courier",
		rules: "Rush.",
		targeting: "none",
		type: "being",
	}),
	hearthplate: card({
		art: "◈",
		attack: 1,
		cost: 3,
		element: "iron",
		energy: 3,
		flavor: "A portable home, if home routinely deflects arrows.",
		grantedKeywords: ["guard"],
		id: "hearthplate",
		name: "Hearthplate",
		rules: "Equipped Being gets +1/+3 and Guard.",
		targeting: "friendlyBeing",
		type: "item",
	}),
	"icicle-stoat": card({
		art: "♟",
		attack: 2,
		cost: 2,
		element: "ice",
		energy: 3,
		flavor: "It keeps one secret frozen under its tongue.",
		id: "icicle-stoat",
		name: "Icicle Stoat",
		rules: "Cool under pressure; colder without it.",
		targeting: "none",
		type: "being",
	}),
	"last-light": card({
		art: "☄",
		cost: 5,
		effects: [{ amount: 6, kind: "damage", recipient: "target" }],
		element: "fire",
		flavor: "The horizon takes one final, personal interest.",
		id: "last-light",
		name: "Last Light",
		rules: "Deal 6 damage to an enemy.",
		targeting: "anyEnemy",
		type: "spell",
	}),
	"kilnback-tortoise": card({
		art: "♜",
		attack: 2,
		cost: 2,
		element: "fire",
		energy: 4,
		flavor: "Its shell holds one cottage fire and several old grudges.",
		id: "kilnback-tortoise",
		keywords: ["guard"],
		name: "Kilnback Tortoise",
		rules: "Guard.",
		targeting: "none",
		type: "being",
	}),
	"many-eyed-moth": card({
		art: "✺",
		attack: 2,
		cost: 2,
		effects: [{ count: 1, kind: "draw" }],
		element: "ether",
		energy: 2,
		flavor: "It sees the thought you almost had.",
		id: "many-eyed-moth",
		name: "Many-Eyed Moth",
		rules: "When summoned, draw 1 card.",
		targeting: "none",
		type: "being",
	}),
	"marrow-hound": card({
		art: "♞",
		attack: 3,
		cost: 2,
		element: "bone",
		energy: 2,
		flavor: "Good hound. Questionable skeleton.",
		id: "marrow-hound",
		name: "Marrow Hound",
		rules: "It always brings something back.",
		targeting: "none",
		type: "being",
	}),
	"mend-the-vessel": card({
		art: "✚",
		cost: 2,
		effects: [{ amount: 4, kind: "heal", recipient: "target" }],
		element: "leaf",
		flavor: "The vessel does not get a vote.",
		id: "mend-the-vessel",
		name: "Mend the Vessel",
		rules: "Restore 4 life to a friendly character.",
		targeting: "friendlyCharacter",
		type: "spell",
	}),
	"mistfin-minnow": card({
		art: "≋",
		attack: 1,
		cost: 1,
		effects: [{ count: 1, kind: "draw" }],
		element: "water",
		energy: 1,
		flavor: "It swims through weather and occasionally correspondence.",
		id: "mistfin-minnow",
		keywords: ["current"],
		name: "Mistfin Minnow",
		rules: "Current. When summoned, draw 1 card.",
		targeting: "none",
		type: "being",
	}),
	"monsoon-in-a-jar": card({
		art: "≋",
		cost: 4,
		effects: [{ amount: 2, kind: "damageAllEnemyBeings" }],
		element: "water",
		flavor: "Open outdoors. Or somewhere you no longer value.",
		id: "monsoon-in-a-jar",
		name: "Monsoon in a Jar",
		rules: "Deal 2 damage to every enemy Being.",
		targeting: "none",
		type: "spell",
	}),
	"old-orchard-tender": card({
		art: "♙",
		attack: 2,
		cost: 3,
		element: "leaf",
		energy: 4,
		flavor: "They prune futures, never branches.",
		id: "old-orchard-tender",
		keywords: ["tend"],
		name: "Old Orchard Tender",
		rules:
			"Tend. The first time each turn it Tends a Being to 2 or more growth, draw a card.",
		targeting: "none",
		type: "being",
	}),
	"riverjaw-newt": card({
		art: "♞",
		attack: 3,
		cost: 3,
		element: "water",
		energy: 4,
		flavor: "Polite enough to wait until the bridge toll is paid.",
		id: "riverjaw-newt",
		keywords: ["current"],
		name: "Riverjaw Newt",
		rules: "Current.",
		targeting: "none",
		type: "being",
	}),
	"rootwoven-buckler": card({
		art: "◈",
		attack: 0,
		cost: 2,
		element: "wood",
		energy: 2,
		flavor: "It grows a handle exactly where you are willing to hold on.",
		grantedKeywords: ["rooted"],
		id: "rootwoven-buckler",
		name: "Rootwoven Buckler",
		rules: "Equipped Being gets +2 Energy and Rooted.",
		targeting: "friendlyBeing",
		type: "item",
	}),
	"riptide-rebuke": card({
		art: "↝",
		cost: 3,
		effects: [{ kind: "returnToHand", recipient: "target" }],
		element: "water",
		flavor: "The river rejects your application.",
		id: "riptide-rebuke",
		name: "Riptide Rebuke",
		rules: "Return an enemy Being to its owner's hand. Its Item is discarded.",
		targeting: "enemyBeing",
		type: "spell",
	}),
	"second-shadow": card({
		art: "◐",
		attack: 1,
		cost: 3,
		element: "ether",
		energy: 2,
		flavor: "Useful when your first shadow is being questioned.",
		grantedKeywords: ["molt"],
		id: "second-shadow",
		name: "Second Shadow",
		rules: "Equipped Being gets +1/+2 and Molt.",
		targeting: "friendlyBeing",
		type: "item",
	}),
	"season-s-turning": card({
		art: "❧",
		cost: 4,
		element: "leaf",
		flavor: "Spring is not gentle. It is merely thorough.",
		id: "season-s-turning",
		name: "Season's Turning",
		rules:
			"Move all growth from your other Beings onto a friendly Being, then restore all of its Energy.",
		targeting: "friendlyBeing",
		type: "spell",
	}),
	"seedling-scout": card({
		art: "♟",
		attack: 1,
		cost: 1,
		element: "leaf",
		energy: 3,
		flavor: "The frontier begins wherever it plants its little flag.",
		id: "seedling-scout",
		keywords: ["tend"],
		name: "Seedling Scout",
		rules: "Tend.",
		targeting: "none",
		type: "being",
	}),
	"skysail-harness": card({
		art: "⌇",
		attack: 1,
		cost: 2,
		element: "air",
		energy: 2,
		flavor: "The straps are reassuringly redundant.",
		id: "skysail-harness",
		name: "Skysail Harness",
		rules: "Equipped Being gets +1/+2.",
		targeting: "friendlyBeing",
		type: "item",
	}),
	"slimebound-ox": card({
		art: "♜",
		attack: 4,
		cost: 4,
		element: "slime",
		energy: 6,
		flavor: "Nothing gets past it. Several things get stuck to it.",
		id: "slimebound-ox",
		keywords: ["guard", "rooted"],
		name: "Slimebound Ox",
		rules: "Guard. Rooted.",
		targeting: "none",
		type: "being",
	}),
	"sporecap-tender": card({
		art: "♙",
		attack: 2,
		cost: 2,
		effects: [{ amount: 2, kind: "heal", recipient: "ownSummoner" }],
		element: "slime",
		energy: 2,
		flavor: "Its remedy is effective, compulsory, and faintly singing.",
		id: "sporecap-tender",
		keywords: ["tend"],
		name: "Sporecap Tender",
		rules: "Tend. When summoned, restore 2 life to your Summoner.",
		targeting: "none",
		type: "being",
	}),
	"sporesick-elk": card({
		art: "♞",
		attack: 5,
		cost: 4,
		effects: [{ amount: 1, kind: "damage", recipient: "ownSummoner" }],
		element: "ether",
		energy: 5,
		flavor: "The antlers bloom. The elk declines to discuss it.",
		id: "sporesick-elk",
		keywords: ["molt"],
		name: "Sporesick Elk",
		rules: "Molt. When summoned, deal 1 damage to your Summoner.",
		targeting: "none",
		type: "being",
	}),
	"spark-toss": card({
		art: "✦",
		cost: 1,
		effects: [{ amount: 2, kind: "damage", recipient: "target" }],
		element: "fire",
		flavor: "A tiny sun with somewhere urgent to be.",
		id: "spark-toss",
		name: "Spark Toss",
		rules: "Deal 2 damage to an enemy.",
		targeting: "anyEnemy",
		type: "spell",
	}),
	"sudden-overgrowth": card({
		art: "❧",
		cost: 3,
		effects: [{ amount: 2, kind: "grow", recipient: "target" }],
		element: "leaf",
		flavor: "One season, delivered without warning.",
		id: "sudden-overgrowth",
		name: "Sudden Overgrowth",
		rules: "Put 2 growth counters on a friendly Being.",
		targeting: "friendlyBeing",
		type: "spell",
	}),
	"sweet-morphology": card({
		art: "✺",
		cost: 4,
		effects: [
			{ attack: 3, energy: 3, kind: "buff", recipient: "target" },
			{ amount: 2, kind: "damage", recipient: "ownSummoner" },
		],
		element: "ether",
		flavor: "You asked for stronger. You did not ask for recognizable.",
		id: "sweet-morphology",
		name: "Sweet Morphology",
		rules: "A friendly Being gets +3/+3. Deal 2 damage to your Summoner.",
		targeting: "friendlyBeing",
		type: "spell",
	}),
	"thought-thorn": card({
		art: "⌁",
		cost: 2,
		effects: [
			{ amount: 2, kind: "damage", recipient: "target" },
			{ count: 1, kind: "draw" },
		],
		element: "ether",
		flavor: "The first symptom is having had the idea already.",
		id: "thought-thorn",
		name: "Thought Thorn",
		rules: "Deal 2 damage to an enemy Summoner. Draw 1 card.",
		targeting: "enemySummoner",
		type: "spell",
	}),
	thornhare: card({
		art: "♞",
		attack: 4,
		cost: 3,
		element: "leaf",
		energy: 3,
		flavor: "Cute from the side that is not currently charging.",
		id: "thornhare",
		name: "Thornhare",
		rules: "Fast enough to make the brambles look stationary.",
		targeting: "none",
		type: "being",
	}),
	"tideglass-lens": card({
		art: "◉",
		attack: 1,
		cost: 3,
		effects: [{ count: 1, kind: "draw" }],
		element: "water",
		energy: 1,
		flavor: "Look through it and see the coast after the coast.",
		grantedKeywords: ["current"],
		id: "tideglass-lens",
		name: "Tideglass Lens",
		rules: "Equipped Being gets +1/+1 and Current. Draw 1 card.",
		targeting: "friendlyBeing",
		type: "item",
	}),
	"unbodying-choir": card({
		art: "♜",
		attack: 6,
		cost: 6,
		element: "ether",
		energy: 7,
		flavor: "Every voice belongs to somebody. Most bodies do not.",
		id: "unbodying-choir",
		keywords: ["guard", "leech"],
		name: "Unbodying Choir",
		rules: "Guard. Leech.",
		targeting: "none",
		type: "being",
	}),
	"velvet-parasite": card({
		art: "♞",
		attack: 3,
		cost: 3,
		element: "ether",
		energy: 4,
		flavor: "Soft as an apology. Just as hungry.",
		id: "velvet-parasite",
		keywords: ["leech", "molt"],
		name: "Velvet Parasite",
		rules: "Leech. Molt.",
		targeting: "none",
		type: "being",
	}),
	"walking-grove": card({
		art: "♜",
		attack: 7,
		cost: 8,
		element: "wood",
		energy: 9,
		flavor: "The oldest border marker has decided the border should move.",
		id: "walking-grove",
		keywords: ["guard", "breakthrough", "rooted"],
		name: "The Walking Grove",
		rules:
			"Guard. Breakthrough. Rooted. Costs 1 less Spark for every 2 growth among your Beings.",
		targeting: "none",
		type: "being",
	}),
	"wildfire-lesson": card({
		art: "☄",
		cost: 4,
		effects: [{ amount: 2, kind: "damageAllEnemyBeings" }],
		element: "fire",
		flavor: "The second lesson is about prevailing winds.",
		id: "wildfire-lesson",
		name: "Wildfire Lesson",
		rules: "Deal 2 damage to every enemy Being.",
		targeting: "none",
		type: "spell",
	}),
} as const satisfies Record<string, SummonersCardDefinition>

const paired = (...cardIds: string[]): string[] =>
	cardIds.flatMap((cardId) => [cardId, cardId])

export const summonersStarterDecks = {
	emberReliquary: {
		accent: "#ff6a3d",
		cardIds: paired(
			"coalcoat-cub",
			"cinderwing-finch",
			"brasshorn-ibex",
			"furnace-fox",
			"ashen-colossus",
			"frontier-flareknife",
			"hearthplate",
			"spark-toss",
			"wildfire-lesson",
			"ash-lesson",
			"last-light",
			"kilnback-tortoise",
		),
		elementLabel: "Fire · Iron",
		id: "emberReliquary",
		name: "Ember Reliquary",
		philosophy:
			"Strike early, spend every Spark, and let Blaze open a second attack.",
		summoner: {
			art: "✦",
			element: "fire",
			name: "Pip",
			power: {
				cost: 2,
				effects: [{ amount: 1, kind: "damage", recipient: "target" }],
				name: "Pocket Ember",
				rules: "Deal 1 damage to an enemy.",
				targeting: "anyEnemy",
			},
			title: "Last Lamplighter",
		},
	},
	outlandChorus: {
		accent: "#d66cff",
		cardIds: paired(
			"dustmote-familiar",
			"many-eyed-moth",
			"marrow-hound",
			"velvet-parasite",
			"sporesick-elk",
			"unbodying-choir",
			"bone-needle",
			"second-shadow",
			"thought-thorn",
			"borrowed-body",
			"sweet-morphology",
			"cancerous-bloom",
		),
		elementLabel: "Ether · Bone",
		id: "outlandChorus",
		name: "Outland Chorus",
		philosophy:
			"Choose survivable fights, Molt into new shapes, and feed on the aftermath.",
		summoner: {
			art: "◉",
			element: "ether",
			name: "Vesper",
			power: {
				cost: 2,
				effects: [
					{ amount: 1, kind: "damage", recipient: "target" },
					{ amount: 1, kind: "heal", recipient: "ownSummoner" },
				],
				name: "Private Thought",
				rules: "Deal 1 damage to an enemy Summoner. Restore 1 life.",
				targeting: "enemySummoner",
			},
			title: "Many-Eyed",
		},
	},
	tidemarkMenagerie: {
		accent: "#38cde0",
		cardIds: paired(
			"mistfin-minnow",
			"icicle-stoat",
			"gullwind-courier",
			"riverjaw-newt",
			"glacier-ram",
			"blue-mile-leviathan",
			"tideglass-lens",
			"skysail-harness",
			"riptide-rebuke",
			"flash-freeze",
			"monsoon-in-a-jar",
			"chart-the-shoals",
		),
		elementLabel: "Water · Ice · Air",
		id: "tidemarkMenagerie",
		name: "Tidemark Menagerie",
		philosophy:
			"Draw deeply, ride the Current twice, and let the tide choose the fight.",
		summoner: {
			art: "≋",
			element: "water",
			name: "Nix",
			power: {
				cost: 2,
				effects: [{ count: 1, kind: "draw" }],
				name: "Read the Current",
				rules: "Draw 1 card.",
				targeting: "none",
			},
			title: "of the Blue Mile",
		},
	},
	verdantCompact: {
		accent: "#9edb43",
		cardIds: [
			"seedling-scout",
			"seedling-scout",
			"seedling-scout",
			"barkhide-mouse",
			"barkhide-mouse",
			"sporecap-tender",
			"sporecap-tender",
			"old-orchard-tender",
			"old-orchard-tender",
			"canopy-stag",
			"canopy-stag",
			"slimebound-ox",
			"walking-grove",
			"rootwoven-buckler",
			"deep-roots",
			"deep-roots",
			"sudden-overgrowth",
			"sudden-overgrowth",
			"briar-challenge",
			"briar-challenge",
			"season-s-turning",
			"fruitful-sacrifice",
			"canopy-muster",
			"green-reprisal",
		],
		elementLabel: "Leaf · Wood · Slime",
		id: "verdantCompact",
		name: "Verdant Compact",
		philosophy:
			"Tend an ecosystem, cross growth thresholds, then harvest or attack.",
		summoner: {
			art: "❧",
			element: "leaf",
			name: "Brindle",
			power: {
				cost: 2,
				effects: [
					{ amount: 1, kind: "grow", recipient: "target" },
					{ amount: 1, kind: "heal", recipient: "target" },
				],
				name: "Tender Growth",
				rules:
					"Put a growth counter on a friendly Being and restore 1 Energy to it.",
				targeting: "friendlyBeing",
			},
			title: "Mossmother",
		},
	},
} as const satisfies Record<SummonersDeckId, SummonersStarterDeckDefinition>

export const SUMMONERS_DECK_IDS = Object.keys(
	summonersStarterDecks,
) as SummonersDeckId[]

export function isSummonersDeckId(input: unknown): input is SummonersDeckId {
	return (
		typeof input === "string" && Object.hasOwn(summonersStarterDecks, input)
	)
}

export function summonersCardDefinition(
	cardId: string,
): SummonersCardDefinition {
	const definition =
		summonersCardCatalog[cardId as keyof typeof summonersCardCatalog]
	if (definition === undefined) {
		throw new Error(`Unknown Summoners card: ${cardId}.`)
	}
	return definition
}
